package imperial.modaclouds.monitoring.datacollectors.basic;

public class Env {

	public static final String MODACLOUDS_KNOWLEDGEBASE_ENDPOINT_IP = "MODACLOUDS_KNOWLEDGEBASE_ENDPOINT_IP";
	public static final String MODACLOUDS_KNOWLEDGEBASE_ENDPOINT_PORT = "MODACLOUDS_KNOWLEDGEBASE_ENDPOINT_PORT";
	public static final String MODACLOUDS_KNOWLEDGEBASE_DATASET_PATH = "MODACLOUDS_KNOWLEDGEBASE_DATASET_PATH";
	public static final String MODACLOUDS_MONITORING_DDA_ENDPOINT_IP = "MODACLOUDS_MONITORING_DDA_ENDPOINT_IP";
	public static final String MODACLOUDS_MONITORING_DDA_ENDPOINT_PORT = "MODACLOUDS_MONITORING_DDA_ENDPOINT_PORT";
	public static final String MODACLOUDS_KNOWLEDGEBASE_SYNC_PERIOD = "MODACLOUDS_KNOWLEDGEBASE_SYNC_PERIOD";
	public static final String MODACLOUDS_MONITORED_APP_ID = "MODACLOUDS_MONITORED_APP_ID";
	public static final String MODACLOUDS_MONITORED_VM_ID = "MODACLOUDS_MONITORED_VM_ID";

	
}
